name: Build and release aab

on:
  pull_request:
    branches: [ release ]
    types: [ closed ]

jobs:
  build:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    
    env:
      LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Decode and Save Keystore File
      run: |
        mkdir -p app/keystore
        echo "${{ secrets.APP_RELEASE_KEY_STORE_BASE_64 }}" | base64 --decode > app/keystore/petid-release.keystore

    - name: Create local.properties
      run: |
        echo "$LOCAL_PROPERTIES" > local.properties
          
    - name: Set up keystore environment variable
      run: echo "KEYSTORE_FILE=$GITHUB_WORKSPACE/app/keystore/petid-release.keystore" >> $GITHUB_ENV

    - name: Set default AAB paths
      run: |
        echo "AAB_DIR=app/build/outputs/bundle/operationRelease" >> $GITHUB_ENV
        echo "AAB_FILE=app-operation-release.aab" >> $GITHUB_ENV
        
    - name: Build Release AAB
      run: ./gradlew bundleOperationRelease --stacktrace --info
      env:
        KEYSTORE_FILE: ${{ env.KEYSTORE_FILE }}
        KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Find AAB file and update paths if needed
      run: |
        echo "Looking for AAB files..."
        AAB_PATH=$(find app/build -name "*.aab" -type f | head -n 1)
        
        if [ -n "$AAB_PATH" ]; then
          # AAB 파일을 찾았을 경우 경로 업데이트
          echo "Found AAB at: $AAB_PATH"
          AAB_DIR=$(dirname "$AAB_PATH")
          AAB_FILE=$(basename "$AAB_PATH")
          echo "AAB_DIR=$AAB_DIR" >> $GITHUB_ENV
          echo "AAB_FILE=$AAB_FILE" >> $GITHUB_ENV
          echo "Updated AAB directory to: $AAB_DIR"
          echo "Updated AAB filename to: $AAB_FILE"
        else
          echo "No AAB file found! Using default paths."
        fi
        
    - name: Sign AAB
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: ${{ env.AAB_DIR }}
        signingKeyBase64: ${{ secrets.APP_RELEASE_KEY_STORE_BASE_64 }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Deploy to Google Play Store
      uses: r0adkll/upload-google-play@v1.1.3
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: com.petid.petid
        releaseFiles: ${{ env.AAB_DIR }}/${{ env.AAB_FILE }}
        track: alpha               # production, internal, alpha, beta
        status: completed
